### ISSUE TITLE
Unable to get list of servers from OneView appliance

### ISSUE THREAD

**Issue by GodfreyAidoo** [HewlettPackard/oneview-powershell-samples#7] opened 2020-02-07 12:39 UTC
[2002071320_HPOV_transcript.log](https://github.com/HewlettPackard/oneview-powershell-samples/files/4170771/2002071320_HPOV_transcript.log)

Able to connect to OneView appliance but not getting the  list of servers through powershell command.

**Comment by ChrisLynchHPE** [comment] 2020-02-07 13:59
Thank you for reporting this issue.  The issue is with the API, in which the PowerShell library tries to filter duplicate entries and avoid the error you are getting. As this isn't an issue with the example script, I have created an issue on the PowerShell library issue tracker, HewlettPackard/POSH-HPOneView#451.

**Comment by ChrisLynchHPE** [comment] 2020-05-01 17:33
I'm closing this issue, as it was addressed in the linked PowerShell library issue.

**Closed as completed by ChrisLynchHPE** 2020-05-01 17:33 UTC
